steps:
  - name: ghcr.io/mansunkuo/code-stingray:0.1.2
    secretEnv: ['GITHUB_TOKEN']
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "HEAD_BRANCH = $_HEAD_BRANCH"
        echo "BASE_BRANCH = $_BASE_BRANCH"
        echo "HEAD_REPO_URL = $_HEAD_REPO_URL"
        echo "PR_NUMBER = $_PR_NUMBER"
        echo "REPO_OWNER = $(echo $REPO_FULL_NAME | cut -d '/' -f 1)"
        echo "REPO_NAME = $REPO_NAME"

        git branch
        git log | head
        git fetch origin $_BASE_BRANCH $_HEAD_BRANCH
        echo "BASE_COMMIT_SHA = $(git rev-parse origin/$_BASE_BRANCH)"
        echo "HEAD_COMMIT_SHA = $(git rev-parse origin/$_HEAD_BRANCH)"

        code-stingray \
          --path . \
          -c1 $(git rev-parse origin/$_BASE_BRANCH) \
          -c2 $(git rev-parse origin/$_HEAD_BRANCH) \
          google_cloud --google_cloud_project $PROJECT_ID \
          github \
            --github_repo_owner $(echo $REPO_FULL_NAME | cut -d '/' -f 1) \
            --github_repo_name $REPO_NAME \
            --github_pr_number $_PR_NUMBER
logsBucket: ${PROJECT_ID}_cloudbuild  # Change it as the Bucket you want to use.
serviceAccount: projects/${PROJECT_ID}/serviceAccounts/${PROJECT_ID}@${PROJECT_ID}.iam.gserviceaccount.com
options:
  logging: GCS_ONLY
  # logging: CLOUD_LOGGINGONLY
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/GITHUB_TOKEN/versions/latest
    env: GITHUB_TOKEN
